package net.sanlite.client.plugins.gauntlet.event;

public enum GauntletEventType
{
	ATTACK_STYLE_SWITCHED,
	PROTECTION_PRAYER_SWITCHED,
	PLAYER_PRAYER_DISABLED,
	CRYSTAL_ATTACK,
	PLAYER_DEATH,
	DEMI_BOSS_SPAWNED,
	DEMI_BOSS_DESPAWNED,
}
