name: SanLite CI - Commit push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1.0.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk+fx

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1.0.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk+fx

      - name: Build with Maven
        run: mvn test
